/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oops_java;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.MessageFormat;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class overall extends javax.swing.JFrame {

    /**
     * Creates new form overall
     */
    Connection con;
    public overall() {
        initComponents();
        String url = "jdbc:mysql://localhost/emarket";
        String user = "root";
        String pass = "";
        try{
            con = DriverManager.getConnection(url, user, pass);
        }catch(Exception ex){
            System.out.println("Error " + ex.getMessage());
        }
        String sql="SELECT prod_name,prod_price,reviews FROM  emarket_table";
        try{
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs=pst.executeQuery();
            DefaultTableModel model= (DefaultTableModel)tblover.getModel();
            model.setRowCount(0);
            //table.setRowHeight(30);
            while(rs.next()){
                model.addRow(new String[]{rs.getString(1),rs.getString(2),rs.getString(3)});
                //model.setRowHeight(40);
            }
        }catch(Exception ex){
            System.out.println("Error : " + ex.getMessage());
        }
        algorithm();
    }
    
    public void algorithm(){
        int row1 = tblover.getRowCount();
        double tot_price = 0, tot_review = 0;
        double avg_price,avg_rev;
        double x = 0;
        double temp;
        DefaultTableModel model= (DefaultTableModel)tblover.getModel();
        //models.addColumn("Overall Rating", new Object[]{x});
        String overall = null;
        for(int i =0;i < row1;i++){
            double val = Double.valueOf(tblover.getValueAt(i,1).toString());
            double rev = Double.valueOf(tblover.getValueAt(i,2).toString());
            tot_price += val;
            tot_review += rev;
        }
        avg_price = tot_price/row1;
        avg_rev = tot_review/row1;
        
        for(int i = 0;i < row1;i++)
        {
            double val = Double.valueOf(tblover.getValueAt(i,1).toString());
            double rev = Double.valueOf(tblover.getValueAt(i,2).toString());
            x = (val * rev)/(avg_price * avg_rev);
            
            //models.insertRow(i, new Object[]{x});
            //models.addRow(new Object[]{null,null,x});
           //models.insertRow(row1,new Object[]{x});
            //tblextra.addRowSelectionInterval(0, row1);
            //tblextra.setAutoCreateRowSorter(true);
            //model.addColumn(new Object[]{x});
            
           // model.addRow(new Object[]{x});
            //model.addRow(new String[]{rs.getString(1),rs.getString(2),rs.getString(3)});
            //model.
            Object[] Overall_rating = {x};
            model.setValueAt(x, i, 3);
            
        }
      }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblover = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnprint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblover.setAutoCreateRowSorter(true);
        tblover.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        tblover.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "prod_name", "prod_price", "prod_rate", "Overall rating"
            }
        ));
        tblover.setRowHeight(30);
        jScrollPane1.setViewportView(tblover);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("CLICK ON THE \"Overall rating\" COLUMN LABEL ONCE TO SORT THE DATA IN ASCENDING OR DECSENDING ORDER.");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setText("jLabel2");

        btnprint.setText("print");
        btnprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(91, 91, 91)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(644, 644, 644)
                        .addComponent(btnprint)))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(btnprint)
                .addGap(55, 55, 55))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprintActionPerformed
        // TODO add your handling code here:
        
        MessageFormat header = new MessageFormat("Hello");
        MessageFormat footer = new MessageFormat("page{0,number,integer}");
        try{
            tblover.print(JTable.PrintMode.FIT_WIDTH,header,footer);
        }catch(Exception e){
            e.getMessage();
        }
    }//GEN-LAST:event_btnprintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(overall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(overall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(overall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(overall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new overall().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnprint;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblover;
    // End of variables declaration//GEN-END:variables
}