/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oops_java;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author user
 */
public class Userreciept_commerce extends javax.swing.JFrame {

    /**
     * Creates new form Userreciept_commerce
     */
    public Userreciept_commerce() {
        initComponents();
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        dataset.setValue(7,"Reviews","HP pavillion");
        dataset.setValue(8,"Reviews","ASUS 14 Zenbook");
        dataset.setValue(7,"Reviews","ASUS Tuf Gaming A17");
        dataset.setValue(6,"Reviews","ASUS Vivobook Pro 15");
        dataset.setValue(10,"Reviews","APPLE 2020 Macbook");
        dataset.setValue(8,"Reviews","ASUS core i7");
        dataset.setValue(9,"Reviews","MacBook air M2");
        dataset.setValue(9,"Reviews","HP spectre x360");
        dataset.setValue(8,"Reviews","ASUS ROG");
        dataset.setValue(10,"Reviews","ASUS Chromebook");
        JFreeChart chart = ChartFactory.createBarChart("E-Commerce Analysis","Brands", "Reviews", dataset, PlotOrientation.VERTICAL, false, true, false);
        CategoryPlot p = chart.getCategoryPlot();
        p.setRangeGridlinePaint(Color.black);
        ChartPanel chart1 = new ChartPanel(chart);
        graphpane.removeAll();
        graphpane.add(chart1,BorderLayout.CENTER);
        graphpane.validate();
        //if(prodnamefield.getText() == "HP Pavillion G6"){
            
            //imagepane.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Documents\\NetBeansProjects\\oops_java\\src\\oops_java\\icons\\hpg6.jpeg"));
        //}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Username = new javax.swing.JLabel();
        usernamefield = new javax.swing.JLabel();
        prodname = new javax.swing.JLabel();
        prodnamefield = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ramfield = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        storefield = new javax.swing.JLabel();
        graphpane = new javax.swing.JPanel();
        imagepane = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Documents\\NetBeansProjects\\oops_java\\src\\oops_java\\icons\\44435f30481d4a13995c7d3584128634.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 170));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 51));
        jLabel2.setText("E - COMMERCE PRODUCT ANALYZER ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 470, 80));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("Contact us : epa@gmail.com");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, 300, 60));

        Username.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Username.setForeground(new java.awt.Color(204, 0, 51));
        Username.setText("USERNAME :");
        jPanel1.add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 160, 50));

        usernamefield.setBackground(new java.awt.Color(255, 204, 204));
        usernamefield.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jPanel1.add(usernamefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 320, 40));

        prodname.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        prodname.setForeground(new java.awt.Color(204, 0, 51));
        prodname.setText("PRODUCT NAME :");
        jPanel1.add(prodname, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 220, 50));

        prodnamefield.setBackground(new java.awt.Color(255, 204, 204));
        prodnamefield.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jPanel1.add(prodnamefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 350, 40));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 51));
        jLabel4.setText("RAM :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, 80, 40));

        ramfield.setBackground(new java.awt.Color(255, 204, 204));
        ramfield.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jPanel1.add(ramfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, 290, 40));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 51));
        jLabel5.setText("STORAGE :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 470, -1, -1));

        storefield.setBackground(new java.awt.Color(255, 204, 204));
        storefield.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jPanel1.add(storefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 460, 270, 40));

        graphpane.setBackground(new java.awt.Color(255, 255, 255));
        graphpane.setForeground(new java.awt.Color(255, 51, 51));
        graphpane.setLayout(new java.awt.BorderLayout());
        jPanel1.add(graphpane, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, 1160, 400));
        jPanel1.add(imagepane, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 250, 310, 290));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 0, 51));
        jButton1.setText("PRINT");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1754, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1453, 1810));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
         printRecord(jPanel1);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Userreciept_commerce.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Userreciept_commerce.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Userreciept_commerce.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Userreciept_commerce.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Userreciept_commerce().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Username;
    private javax.swing.JPanel graphpane;
    public javax.swing.JLabel imagepane;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel prodname;
    public javax.swing.JLabel prodnamefield;
    public javax.swing.JLabel ramfield;
    public javax.swing.JLabel storefield;
    public javax.swing.JLabel usernamefield;
    // End of variables declaration//GEN-END:variables

    private void printRecord(final JPanel panel){
        PrinterJob printerJob = PrinterJob.getPrinterJob();
        printerJob.setJobName("Print Record");
        printerJob.setPrintable(new Printable(){
            public int print(Graphics graphics,PageFormat pageFormat,int pageIndex) throws PrinterException {
               if(pageIndex > 0){
                   return Printable.NO_SUCH_PAGE;
               }
               
               Graphics2D graphics2D = (Graphics2D)graphics;
               graphics2D.translate(pageFormat.getImageableX()*2,pageFormat.getImageableY()*2);
               
               graphics2D.scale(0.5, 0.5);
               panel.paint(graphics2D);
               return Printable.PAGE_EXISTS;
            }
        });
        boolean returningResult = printerJob.printDialog();
        if(returningResult){
            try{
                printerJob.print();
            }catch(PrinterException printerException){
                JOptionPane.showMessageDialog(this,"Print Error: " + printerException.getMessage());
            }
        }
    }

}
